#!/bin/bash

set -e

flex lexical.l
yacc --report state syntatic.y
gcc  y.tab.c yyerror.c main.c -lfl

set +e

for teste in tests/*.mp; do
    echo "$teste"
    ./a.out < $teste > output/$(basename $teste .mp).mp 2>&1
#    ./a.out < output/$(basename $teste .mp).mp > output/$(basename $teste .mp).mp.mp
done

