#!/bin/bash

set -e

make

set +e

for teste in tests/*.mp; do
    echo "$teste"
    ./syntatic < $teste > output/$(basename $teste .mp).mp
    #./syntatic < output/$(basename $teste .mp).mp > output/$(basename $teste .mp).mp.mp
done

